ROWS = 15
COLUMNS = 15
TILE_SIZE = 48
SIDE_PANEL = 300
SCREEN_WIDTH = TILE_SIZE * COLUMNS
SCREEN_HEIGHT = TILE_SIZE * ROWS
FPS = 60
HEALTH = 100
MONEY = 650

# Enemy constants
SPAWN_COOLDOWN = 400

# Turret constants
ANIMATION_STEPS = 8
ANIMATION_DELAY = 15
TURRET_LEVELS = 4
BUY_COST = 200
UPGRADE_COST = 100
KILL_REWARD = 1
DAMAGE = 5
